nginx:
  build: ./nginx
  links:
    - jenkins-master
  ports:
    - 80:80

jenkins-master:
  image: jenkinsci/jenkins:lts
  privileged: true
  links:
    - jenkins-slave
  ports:
    - 8080
    - 5000
  environment:
    JAVA_OPTS: -Djenkins.install.runSetupWizard=false

jenkins-slave:
  build: ./jenkins-slave
  links:
    - sonarqube
  ports:
    - 22

sonarqube:
  image: sonarqube
  ports:
    - 9000:9000
    - 9092:9092

nexus:
  image: sonatype/nexus:oss
  ports:
    - 8081:8081
