# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos-1611-02"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.define "docker_host" do |docker_host|
    docker_host.vm.provision "shell", path: "./init.sh"
    docker_host.vm.network "public_network", ip: "192.168.1.56"
  end

end
