# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos7.1"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  # etcd:
  config.vm.define "etcd" do |etcd|
    etcd.vm.network "public_network", ip: "192.168.1.20"
		etcd.vm.provision "shell", path: "./init-etcd.sh"
  end

  # master:
  config.vm.define "master" do |master|
    master.vm.network "public_network", ip: "192.168.1.21"
		master.vm.provision "shell", path: "./init-master.sh"
  end

  # worker:
  config.vm.define "worker" do |worker|
    worker.vm.network "public_network", ip: "192.168.1.22"
		worker.vm.provision "shell", path: "./init-worker.sh"
  end

end
